services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    restart: unless-stopped
    ports:
      - '9100:9100'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_PORT: 9100
      KC_LOG_CONSOLE_COLOR: 'true'
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -ex
        /opt/keycloak/bin/kc.sh build
        /opt/keycloak/bin/kc.sh start-dev --import-realm

    volumes:
      - ./.docker/keycloak-config/:/opt/keycloak/data/import/:ro
        
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gisapply}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gisapply-password}
      POSTGRES_DB: ${POSTGRES_DB:-gisapply}
    #volumes:
    #  - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT:-18080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER:-gisapply}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-gisapply-password}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-dracula}
      ADMINER_PLUGINS: ${ADMINER_PLUGINS:-tables-filter tinymce}

  minio:
    image: bitnami/minio:latest
    #volumes:
    #  - minio:/bitnami/minio/data
    ports:
      - ${MINIO_PORT:-19000}:9000
      - ${MINIO_PORT_INTERNAL:-9001}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
      MINIO_BROWSER_SESSION_DURATION: ${MINIO_BROWSER_SESSION_DURATION:-7d}
      MINIO_BROWSER_LOGIN_ANIMATION: ${MINIO_BROWSER_LOGIN_ANIMATION:-off}

  tracking:
    image: jaegertracing/all-in-one:latest
    ports:
      - '4318:4318' # OpenTelemetry receiver
      - '14268:14268' # Jaeger receiver
      - '16686:16686' # Jaeger UI
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
      
        
#volumes:
  #db: { }
  #minio: { }