global:
  version: "2025.4.6"
  labels:
    app: gis-application
    team: adorsys-gis

app:
  defaultPodOptions:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000

  controllers:
    main:
      type: deployment
      replicas: 1
      initContainers:
        migrations:
          image:
            repository: ghcr.io/adorsys-gis/gis-applications-migrations
            tag: "{{ .Values.global.version }}"
            pullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: '{{ .Release.Name }}-db'
      containers:
        app:
          image:
            repository: ghcr.io/adorsys-gis/gis-applications
            tag: "{{ .Values.global.version }}"
            pullPolicy: IfNotPresent

          # -- ConfigMap to be loaded as environment variables
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-config'
            - configMapRef:
                name: '{{ .Release.Name }}-redis'
            - configMapRef:
                name: '{{ .Release.Name }}-otel'
            - secretRef:
                name: '{{ .Release.Name }}-s3'
            - secretRef:
                name: '{{ .Release.Name }}-smtp'
            - secretRef:
                name: '{{ .Release.Name }}-auth'
            - secretRef:
                name: '{{ .Release.Name }}-db'
            - secretRef:
                name: '{{ .Release.Name }}-redis'
            - secretRef:
                name: '{{ .Release.Name }}-ai'

  service:
    app:
      enabled: true
      annotations: { }
      nameOverride: service
      type: ClusterIP
      controller: main
      ports:
        http:
          enabled: true
          port: 3000
          targetPort: 3000

  ingress:
    app:
      enabled: true
      annotations: { }
      nameOverride: ingress
      #className: 'nginx'
      hosts:
        - host: apply.example.com
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - secretName: apply-example-com-secret
          hosts:
            - apply.example.com

  configMaps:
    config:
      enabled: true
      annotations:
        description: 'Common configuration for the GIS Application app.'
      data:
        AUTH_KEYCLOAK_ISSUER: https://kec.example.com/realms/main

        AUTH_SESSION_MAX_AGE: '2592000'
        AUTH_SESSION_UPDATE_AGE: '2592000'

        S3_ENDPOINT: s3.example.com
        S3_PORT: '443'
        S3_SCHEME: https
        S3_BUCKET: gis-applications
        S3_CDN_URL: https://s3.example.com

        APP_URL: https://apply.example.com

        SMTP_FROM: 'Sender Name <sender@server.com>'
        SMTP_CC: 'GIS Group <cc@server.com>'
        SMTP_REPLY_TO: 'Stephane Segning <stephane@segning.com>'

        APP_LAST_APPLICATION_DATE: '2026-01-31'
    redis:
      enabled: true
      annotations:
        description: 'Redis configuration for the GIS Application app.'
      data:
        REDIS_PREFIX: 'sschool'
    otel:
      enabled: true
      annotations:
        description: 'OTEL configuration for the GIS Application app.'
      data:
        OTEL_EXPORTER_OTLP_ENDPOINT: 'https://otel.example.com'

  secrets:
    s3:
      enabled: true
      annotations:
        description: 'S3 configuration for the GIS Application app.'
      stringData:
        S3_ACCESS_KEY: 'minio'
        S3_SECRET_KEY: 'minio123'
    smtp:
      enabled: true
      annotations:
        description: 'SMTP configuration for the GIS Application app.'
      stringData:
        SMTP_URL: 'smtp+ssl://user:password@smtp.example:582'
    auth:
      enabled: true
      annotations:
        description: 'Auth configuration for the GIS Application app.'
      stringData:
        AUTH_SECRET: 'gfhZ+94pqhGDi03RCD/6klIbTd92V5yA8G+oEN9c6pk='
        AUTH_KEYCLOAK_ID: 'gis-applications'
        AUTH_KEYCLOAK_SECRET: 'someSecret'
    db:
      enabled: true
      annotations:
        description: 'Auth configuration for the GIS Application app.'
      stringData:
        DATABASE_URL: 'postgresql+ssl://gisapply:gisapply-password@localhost:5432/gisapply?schema=public'
    redis:
      stringData:
        REDIS_URL: 'redis://${redis_host}:${redis_port}'
    ai:
      stringData:
        OPENAI_KEY: ""
        OPENAI_URL: ""

  networkpolicies:
    main:
      enabled: true
      controller: main
      policyTypes:
        - Ingress
      rules:
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: gis-application
            ports:
              - protocol: TCP
                port: 3000
